### PR TITLE
Travis fix error

### PR DESCRIPTION
**Pull request by MaherJendoubi**
Deleted .npmrc files in order to fix Travis error

### CODE REVIEW

**Comment by MaherJendoubi** [comment]
Hi @iamssen, please review :)

**Comment by iamssen** [comment]
Thank you, @MaherJendoubi , for your Pull Request.

But, these .npmrc files are in use.

I have multiple NPM accounts, so I have to use multiple NPM_TOKENs.

Deleting these .npmrc files makes it difficult to access the NPM @lunit account on my local computer.

If you use this repository and these .npmrc files are causing problems, please tell me. I will find another way.

**Comment by MaherJendoubi** [comment]
Thank you for the reply @iamssen. Actually, these .npmrc files are causing problems locally. I created an issue to dig in it.

**Comment by iamssen** [comment]
@MaherJendoubi `NPM_LUNIT_TOKEN` seems to be an inconvenience for developers who fork. It would be nice to remove the .npmrc files.

Thank you for the issue. 😀

**Pull request merged**
